# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_stages: [commit]
default_language_version:
  node: "16.16.0"
  python: "python3.9"
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.3.0"
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: pretty-format-json
        args:
          - "--autofix"
          - "--no-sort-keys"
          - "--no-ensure-ascii"

  - repo: https://github.com/codespell-project/codespell
    rev: "v2.1.0"
    hooks:
      - id: codespell
        args: ["-w"]

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.34.0
    hooks:
    - id: markdownlint
      args:
        - "--fix"

  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 3.0.0
    hooks:
      - id: bundler-audit

  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.0.0
    hooks:
      - id: commitlint
        stages: [commit-msg]
        additional_dependencies: ["@commitlint/config-angular"]
